/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ABoolTerm extends PTerm
{
    private PBoole _boole_;

    public ABoolTerm()
    {
        // Constructor
    }

    public ABoolTerm(
        @SuppressWarnings("hiding") PBoole _boole_)
    {
        // Constructor
        setBoole(_boole_);

    }

    @Override
    public Object clone()
    {
        return new ABoolTerm(
            cloneNode(this._boole_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolTerm(this);
    }

    public PBoole getBoole()
    {
        return this._boole_;
    }

    public void setBoole(PBoole node)
    {
        if(this._boole_ != null)
        {
            this._boole_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boole_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boole_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boole_ == child)
        {
            this._boole_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boole_ == oldChild)
        {
            setBoole((PBoole) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
