/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class AMathfctsTerm extends PTerm
{
    private PMathfcts _mathfcts_;

    public AMathfctsTerm()
    {
        // Constructor
    }

    public AMathfctsTerm(
        @SuppressWarnings("hiding") PMathfcts _mathfcts_)
    {
        // Constructor
        setMathfcts(_mathfcts_);

    }

    @Override
    public Object clone()
    {
        return new AMathfctsTerm(
            cloneNode(this._mathfcts_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMathfctsTerm(this);
    }

    public PMathfcts getMathfcts()
    {
        return this._mathfcts_;
    }

    public void setMathfcts(PMathfcts node)
    {
        if(this._mathfcts_ != null)
        {
            this._mathfcts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mathfcts_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mathfcts_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mathfcts_ == child)
        {
            this._mathfcts_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mathfcts_ == oldChild)
        {
            setMathfcts((PMathfcts) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
