/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ANotNeg extends PNeg
{
    private TNot _not_;
    private PNeg _exp_;

    public ANotNeg()
    {
        // Constructor
    }

    public ANotNeg(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PNeg _exp_)
    {
        // Constructor
        setNot(_not_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new ANotNeg(
            cloneNode(this._not_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotNeg(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PNeg getExp()
    {
        return this._exp_;
    }

    public void setExp(PNeg node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PNeg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
