/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import java.util.*;
import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class AParams extends PParams
{
    private PParam _param_;
    private final LinkedList<PAdditionalParam> _additionalParams_ = new LinkedList<PAdditionalParam>();

    public AParams()
    {
        // Constructor
    }

    public AParams(
        @SuppressWarnings("hiding") PParam _param_,
        @SuppressWarnings("hiding") List<?> _additionalParams_)
    {
        // Constructor
        setParam(_param_);

        setAdditionalParams(_additionalParams_);

    }

    @Override
    public Object clone()
    {
        return new AParams(
            cloneNode(this._param_),
            cloneList(this._additionalParams_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParams(this);
    }

    public PParam getParam()
    {
        return this._param_;
    }

    public void setParam(PParam node)
    {
        if(this._param_ != null)
        {
            this._param_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._param_ = node;
    }

    public LinkedList<PAdditionalParam> getAdditionalParams()
    {
        return this._additionalParams_;
    }

    public void setAdditionalParams(List<?> list)
    {
        for(PAdditionalParam e : this._additionalParams_)
        {
            e.parent(null);
        }
        this._additionalParams_.clear();

        for(Object obj_e : list)
        {
            PAdditionalParam e = (PAdditionalParam) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._additionalParams_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._param_)
            + toString(this._additionalParams_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._param_ == child)
        {
            this._param_ = null;
            return;
        }

        if(this._additionalParams_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._param_ == oldChild)
        {
            setParam((PParam) newChild);
            return;
        }

        for(ListIterator<PAdditionalParam> i = this._additionalParams_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAdditionalParam) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
