/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class APenfctInstr extends PInstr
{
    private PPenfct _penfct_;
    private TSc _sc_;

    public APenfctInstr()
    {
        // Constructor
    }

    public APenfctInstr(
        @SuppressWarnings("hiding") PPenfct _penfct_,
        @SuppressWarnings("hiding") TSc _sc_)
    {
        // Constructor
        setPenfct(_penfct_);

        setSc(_sc_);

    }

    @Override
    public Object clone()
    {
        return new APenfctInstr(
            cloneNode(this._penfct_),
            cloneNode(this._sc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPenfctInstr(this);
    }

    public PPenfct getPenfct()
    {
        return this._penfct_;
    }

    public void setPenfct(PPenfct node)
    {
        if(this._penfct_ != null)
        {
            this._penfct_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._penfct_ = node;
    }

    public TSc getSc()
    {
        return this._sc_;
    }

    public void setSc(TSc node)
    {
        if(this._sc_ != null)
        {
            this._sc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._penfct_)
            + toString(this._sc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._penfct_ == child)
        {
            this._penfct_ = null;
            return;
        }

        if(this._sc_ == child)
        {
            this._sc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._penfct_ == oldChild)
        {
            setPenfct((PPenfct) newChild);
            return;
        }

        if(this._sc_ == oldChild)
        {
            setSc((TSc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
