/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ASetwidthPenfct extends PPenfct
{
    private TSetWidth _setWidth_;
    private TLPar _lPar_;
    private PExp _width_;
    private TRPar _rPar_;

    public ASetwidthPenfct()
    {
        // Constructor
    }

    public ASetwidthPenfct(
        @SuppressWarnings("hiding") TSetWidth _setWidth_,
        @SuppressWarnings("hiding") TLPar _lPar_,
        @SuppressWarnings("hiding") PExp _width_,
        @SuppressWarnings("hiding") TRPar _rPar_)
    {
        // Constructor
        setSetWidth(_setWidth_);

        setLPar(_lPar_);

        setWidth(_width_);

        setRPar(_rPar_);

    }

    @Override
    public Object clone()
    {
        return new ASetwidthPenfct(
            cloneNode(this._setWidth_),
            cloneNode(this._lPar_),
            cloneNode(this._width_),
            cloneNode(this._rPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASetwidthPenfct(this);
    }

    public TSetWidth getSetWidth()
    {
        return this._setWidth_;
    }

    public void setSetWidth(TSetWidth node)
    {
        if(this._setWidth_ != null)
        {
            this._setWidth_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setWidth_ = node;
    }

    public TLPar getLPar()
    {
        return this._lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(this._lPar_ != null)
        {
            this._lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lPar_ = node;
    }

    public PExp getWidth()
    {
        return this._width_;
    }

    public void setWidth(PExp node)
    {
        if(this._width_ != null)
        {
            this._width_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._width_ = node;
    }

    public TRPar getRPar()
    {
        return this._rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(this._rPar_ != null)
        {
            this._rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._setWidth_)
            + toString(this._lPar_)
            + toString(this._width_)
            + toString(this._rPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._setWidth_ == child)
        {
            this._setWidth_ = null;
            return;
        }

        if(this._lPar_ == child)
        {
            this._lPar_ = null;
            return;
        }

        if(this._width_ == child)
        {
            this._width_ = null;
            return;
        }

        if(this._rPar_ == child)
        {
            this._rPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._setWidth_ == oldChild)
        {
            setSetWidth((TSetWidth) newChild);
            return;
        }

        if(this._lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(this._width_ == oldChild)
        {
            setWidth((PExp) newChild);
            return;
        }

        if(this._rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
