/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ASetcolorPenfct extends PPenfct
{
    private TSetColor _setColor_;
    private TLPar _lPar_;
    private PExp _color_;
    private TRPar _rPar_;

    public ASetcolorPenfct()
    {
        // Constructor
    }

    public ASetcolorPenfct(
        @SuppressWarnings("hiding") TSetColor _setColor_,
        @SuppressWarnings("hiding") TLPar _lPar_,
        @SuppressWarnings("hiding") PExp _color_,
        @SuppressWarnings("hiding") TRPar _rPar_)
    {
        // Constructor
        setSetColor(_setColor_);

        setLPar(_lPar_);

        setColor(_color_);

        setRPar(_rPar_);

    }

    @Override
    public Object clone()
    {
        return new ASetcolorPenfct(
            cloneNode(this._setColor_),
            cloneNode(this._lPar_),
            cloneNode(this._color_),
            cloneNode(this._rPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASetcolorPenfct(this);
    }

    public TSetColor getSetColor()
    {
        return this._setColor_;
    }

    public void setSetColor(TSetColor node)
    {
        if(this._setColor_ != null)
        {
            this._setColor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setColor_ = node;
    }

    public TLPar getLPar()
    {
        return this._lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(this._lPar_ != null)
        {
            this._lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lPar_ = node;
    }

    public PExp getColor()
    {
        return this._color_;
    }

    public void setColor(PExp node)
    {
        if(this._color_ != null)
        {
            this._color_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._color_ = node;
    }

    public TRPar getRPar()
    {
        return this._rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(this._rPar_ != null)
        {
            this._rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._setColor_)
            + toString(this._lPar_)
            + toString(this._color_)
            + toString(this._rPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._setColor_ == child)
        {
            this._setColor_ = null;
            return;
        }

        if(this._lPar_ == child)
        {
            this._lPar_ = null;
            return;
        }

        if(this._color_ == child)
        {
            this._color_ = null;
            return;
        }

        if(this._rPar_ == child)
        {
            this._rPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._setColor_ == oldChild)
        {
            setSetColor((TSetColor) newChild);
            return;
        }

        if(this._lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(this._color_ == oldChild)
        {
            setColor((PExp) newChild);
            return;
        }

        if(this._rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
