/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleSum extends PSum
{
    private PNeg _neg_;

    public ASimpleSum()
    {
        // Constructor
    }

    public ASimpleSum(
        @SuppressWarnings("hiding") PNeg _neg_)
    {
        // Constructor
        setNeg(_neg_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleSum(
            cloneNode(this._neg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleSum(this);
    }

    public PNeg getNeg()
    {
        return this._neg_;
    }

    public void setNeg(PNeg node)
    {
        if(this._neg_ != null)
        {
            this._neg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._neg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._neg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._neg_ == child)
        {
            this._neg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._neg_ == oldChild)
        {
            setNeg((PNeg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
