/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TCanvas extends Token
{
    public TCanvas()
    {
        super.setText("canvas");
    }

    public TCanvas(int line, int pos)
    {
        super.setText("canvas");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCanvas(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCanvas(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCanvas text.");
    }
}
