/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TCos extends Token
{
    public TCos()
    {
        super.setText("cos");
    }

    public TCos(int line, int pos)
    {
        super.setText("cos");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCos(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCos(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCos text.");
    }
}
