/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TDessinart extends Token
{
    public TDessinart()
    {
        super.setText("dessinart");
    }

    public TDessinart(int line, int pos)
    {
        super.setText("dessinart");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDessinart(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDessinart(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDessinart text.");
    }
}
