/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TPencil extends Token
{
    public TPencil()
    {
        super.setText("pencil");
    }

    public TPencil(int line, int pos)
    {
        super.setText("pencil");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPencil(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPencil(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPencil text.");
    }
}
