/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TRandomcent extends Token
{
    public TRandomcent()
    {
        super.setText("random100");
    }

    public TRandomcent(int line, int pos)
    {
        super.setText("random100");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRandomcent(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRandomcent(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRandomcent text.");
    }
}
