/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TRandomdix extends Token
{
    public TRandomdix()
    {
        super.setText("random10");
    }

    public TRandomdix(int line, int pos)
    {
        super.setText("random10");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRandomdix(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRandomdix(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRandomdix text.");
    }
}
