/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TReplace extends Token
{
    public TReplace()
    {
        super.setText("replace");
    }

    public TReplace(int line, int pos)
    {
        super.setText("replace");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReplace(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReplace(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReplace text.");
    }
}
