/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TRoundfive extends Token
{
    public TRoundfive()
    {
        super.setText("roundFive");
    }

    public TRoundfive(int line, int pos)
    {
        super.setText("roundFive");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRoundfive(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRoundfive(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRoundfive text.");
    }
}
