/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TSetWidth extends Token
{
    public TSetWidth()
    {
        super.setText("setWidth");
    }

    public TSetWidth(int line, int pos)
    {
        super.setText("setWidth");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSetWidth(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSetWidth(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSetWidth text.");
    }
}
