/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TSetColor extends Token
{
    public TSetColor()
    {
        super.setText("setColor");
    }

    public TSetColor(int line, int pos)
    {
        super.setText("setColor");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSetColor(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSetColor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSetColor text.");
    }
}
