/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TTan extends Token
{
    public TTan()
    {
        super.setText("tan");
    }

    public TTan(int line, int pos)
    {
        super.setText("tan");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTan(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTan(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTan text.");
    }
}
