/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.node;

import dessinart.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TWait extends Token
{
    public TWait()
    {
        super.setText("wait");
    }

    public TWait(int line, int pos)
    {
        super.setText("wait");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TWait(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTWait(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TWait text.");
    }
}
