/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.parser;

import dessinart.syntax.node.*;
import dessinart.syntax.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTAssign(@SuppressWarnings("unused") TAssign node)
    {
        this.index = 0;
    }

    @Override
    public void caseTDivide(@SuppressWarnings("unused") TDivide node)
    {
        this.index = 1;
    }

    @Override
    public void caseTLBr(@SuppressWarnings("unused") TLBr node)
    {
        this.index = 2;
    }

    @Override
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
    {
        this.index = 3;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 4;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 5;
    }

    @Override
    public void caseTRBr(@SuppressWarnings("unused") TRBr node)
    {
        this.index = 6;
    }

    @Override
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
    {
        this.index = 7;
    }

    @Override
    public void caseTStar(@SuppressWarnings("unused") TStar node)
    {
        this.index = 8;
    }

    @Override
    public void caseTSc(@SuppressWarnings("unused") TSc node)
    {
        this.index = 9;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 10;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 11;
    }

    @Override
    public void caseTNot(@SuppressWarnings("unused") TNot node)
    {
        this.index = 12;
    }

    @Override
    public void caseTEq(@SuppressWarnings("unused") TEq node)
    {
        this.index = 13;
    }

    @Override
    public void caseTLt(@SuppressWarnings("unused") TLt node)
    {
        this.index = 14;
    }

    @Override
    public void caseTGt(@SuppressWarnings("unused") TGt node)
    {
        this.index = 15;
    }

    @Override
    public void caseTDo(@SuppressWarnings("unused") TDo node)
    {
        this.index = 16;
    }

    @Override
    public void caseTEnd(@SuppressWarnings("unused") TEnd node)
    {
        this.index = 17;
    }

    @Override
    public void caseTFor(@SuppressWarnings("unused") TFor node)
    {
        this.index = 18;
    }

    @Override
    public void caseTWhile(@SuppressWarnings("unused") TWhile node)
    {
        this.index = 19;
    }

    @Override
    public void caseTFalse(@SuppressWarnings("unused") TFalse node)
    {
        this.index = 20;
    }

    @Override
    public void caseTTrue(@SuppressWarnings("unused") TTrue node)
    {
        this.index = 21;
    }

    @Override
    public void caseTElif(@SuppressWarnings("unused") TElif node)
    {
        this.index = 22;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 23;
    }

    @Override
    public void caseTThen(@SuppressWarnings("unused") TThen node)
    {
        this.index = 24;
    }

    @Override
    public void caseTReturn(@SuppressWarnings("unused") TReturn node)
    {
        this.index = 25;
    }

    @Override
    public void caseTCanvas(@SuppressWarnings("unused") TCanvas node)
    {
        this.index = 26;
    }

    @Override
    public void caseTPencil(@SuppressWarnings("unused") TPencil node)
    {
        this.index = 27;
    }

    @Override
    public void caseTColor(@SuppressWarnings("unused") TColor node)
    {
        this.index = 28;
    }

    @Override
    public void caseTDefine(@SuppressWarnings("unused") TDefine node)
    {
        this.index = 29;
    }

    @Override
    public void caseTImport(@SuppressWarnings("unused") TImport node)
    {
        this.index = 30;
    }

    @Override
    public void caseTDessinart(@SuppressWarnings("unused") TDessinart node)
    {
        this.index = 31;
    }

    @Override
    public void caseTSketch(@SuppressWarnings("unused") TSketch node)
    {
        this.index = 32;
    }

    @Override
    public void caseTFunc(@SuppressWarnings("unused") TFunc node)
    {
        this.index = 33;
    }

    @Override
    public void caseTInt(@SuppressWarnings("unused") TInt node)
    {
        this.index = 34;
    }

    @Override
    public void caseTDouble(@SuppressWarnings("unused") TDouble node)
    {
        this.index = 35;
    }

    @Override
    public void caseTBoolean(@SuppressWarnings("unused") TBoolean node)
    {
        this.index = 36;
    }

    @Override
    public void caseTReplace(@SuppressWarnings("unused") TReplace node)
    {
        this.index = 37;
    }

    @Override
    public void caseTMove(@SuppressWarnings("unused") TMove node)
    {
        this.index = 38;
    }

    @Override
    public void caseTDraw(@SuppressWarnings("unused") TDraw node)
    {
        this.index = 39;
    }

    @Override
    public void caseTDrawTo(@SuppressWarnings("unused") TDrawTo node)
    {
        this.index = 40;
    }

    @Override
    public void caseTSetColor(@SuppressWarnings("unused") TSetColor node)
    {
        this.index = 41;
    }

    @Override
    public void caseTSetWidth(@SuppressWarnings("unused") TSetWidth node)
    {
        this.index = 42;
    }

    @Override
    public void caseTPower(@SuppressWarnings("unused") TPower node)
    {
        this.index = 43;
    }

    @Override
    public void caseTRoundfive(@SuppressWarnings("unused") TRoundfive node)
    {
        this.index = 44;
    }

    @Override
    public void caseTRoundten(@SuppressWarnings("unused") TRoundten node)
    {
        this.index = 45;
    }

    @Override
    public void caseTRoundhund(@SuppressWarnings("unused") TRoundhund node)
    {
        this.index = 46;
    }

    @Override
    public void caseTSin(@SuppressWarnings("unused") TSin node)
    {
        this.index = 47;
    }

    @Override
    public void caseTCos(@SuppressWarnings("unused") TCos node)
    {
        this.index = 48;
    }

    @Override
    public void caseTTan(@SuppressWarnings("unused") TTan node)
    {
        this.index = 49;
    }

    @Override
    public void caseTLog(@SuppressWarnings("unused") TLog node)
    {
        this.index = 50;
    }

    @Override
    public void caseTIdent(@SuppressWarnings("unused") TIdent node)
    {
        this.index = 51;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 52;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 53;
    }
}
