/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.lexer;

import java.io.*;
import dessinart.syntax.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssign(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDivide(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBr(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBr(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStar(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSc(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNot(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEq(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLt(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGt(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDo(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnd(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFor(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalse(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTrue(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElif(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThen(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReturn(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCanvas(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPencil(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColor(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDefine(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TImport(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDessinart(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSketch(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFunc(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInt(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDouble(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolean(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReplace(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMove(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDraw(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDrawTo(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetColor(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetWidth(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPower(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRoundfive(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRoundten(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRoundhund(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSin(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCos(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTan(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLog(line, pos); }
    Token new51(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new52(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }
    Token new53(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCommentMulti(text, line, pos); }
    Token new54(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdent(text, line, pos); }
    Token new55(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {40, 40, 6}, {41, 41, 7}, {42, 42, 8}, {43, 43, 9}, {44, 44, 10}, {45, 45, 11}, {46, 46, 12}, {47, 47, 13}, {48, 57, 14}, {59, 59, 15}, {60, 60, 16}, {61, 61, 17}, {62, 62, 18}, {65, 90, 19}, {97, 97, 19}, {98, 98, 20}, {99, 99, 21}, {100, 100, 22}, {101, 101, 23}, {102, 102, 24}, {103, 104, 19}, {105, 105, 25}, {106, 107, 19}, {108, 108, 26}, {109, 109, 27}, {110, 111, 19}, {112, 112, 28}, {113, 113, 19}, {114, 114, 29}, {115, 115, 30}, {116, 116, 31}, {117, 118, 19}, {119, 119, 32}, {120, 122, 19}, {123, 123, 33}, {125, 125, 34}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 35}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{42, 42, 36}, {47, 47, 37}, },
            {{48, 57, 14}, },
            {},
            {},
            {{61, 61, 38}, },
            {},
            {{48, 57, 39}, {65, 90, 40}, {97, 122, 40}, },
            {{48, 90, -21}, {97, 110, 40}, {111, 111, 41}, {112, 122, 40}, },
            {{48, 90, -21}, {97, 97, 42}, {98, 110, 40}, {111, 111, 43}, {112, 122, 40}, },
            {{48, 90, -21}, {97, 100, 40}, {101, 101, 44}, {102, 110, 40}, {111, 111, 45}, {112, 113, 40}, {114, 114, 46}, {115, 122, 40}, },
            {{48, 90, -21}, {97, 107, 40}, {108, 108, 47}, {109, 109, 40}, {110, 110, 48}, {111, 122, 40}, },
            {{48, 90, -21}, {97, 97, 49}, {98, 110, 40}, {111, 111, 50}, {112, 116, 40}, {117, 117, 51}, {118, 122, 40}, },
            {{48, 90, -21}, {97, 101, 40}, {102, 102, 52}, {103, 108, 40}, {109, 109, 53}, {110, 110, 54}, {111, 122, 40}, },
            {{48, 110, -22}, {111, 111, 55}, {112, 122, 40}, },
            {{48, 110, -22}, {111, 111, 56}, {112, 122, 40}, },
            {{48, 100, -24}, {101, 101, 57}, {102, 110, 40}, {111, 111, 58}, {112, 122, 40}, },
            {{48, 100, -24}, {101, 101, 59}, {102, 110, 40}, {111, 111, 60}, {112, 122, 40}, },
            {{48, 100, -24}, {101, 101, 61}, {102, 104, 40}, {105, 105, 62}, {106, 106, 40}, {107, 107, 63}, {108, 122, 40}, },
            {{48, 90, -21}, {97, 97, 64}, {98, 103, 40}, {104, 104, 65}, {105, 113, 40}, {114, 114, 66}, {115, 122, 40}, },
            {{48, 90, -21}, {97, 103, 40}, {104, 104, 67}, {105, 122, 40}, },
            {},
            {},
            {{9, 32, -2}, },
            {{32, 41, 68}, {42, 42, 69}, {43, 126, 68}, },
            {{10, 10, 70}, {13, 13, 71}, {32, 126, 72}, },
            {},
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 110, -22}, {111, 111, 73}, {112, 122, 40}, },
            {{48, 90, -21}, {97, 109, 40}, {110, 110, 74}, {111, 122, 40}, },
            {{48, 107, -25}, {108, 108, 75}, {109, 114, 40}, {115, 115, 76}, {116, 122, 40}, },
            {{48, 101, -27}, {102, 102, 77}, {103, 114, 40}, {115, 115, 78}, {116, 122, 40}, },
            {{48, 90, -21}, {97, 116, 40}, {117, 117, 79}, {118, 122, 40}, },
            {{48, 90, -21}, {97, 97, 80}, {98, 122, 40}, },
            {{48, 90, -21}, {97, 104, 40}, {105, 105, 81}, {106, 122, 40}, },
            {{48, 90, -21}, {97, 99, 40}, {100, 100, 82}, {101, 122, 40}, },
            {{48, 107, -25}, {108, 108, 83}, {109, 122, 40}, },
            {{48, 90, -21}, {97, 113, 40}, {114, 114, 84}, {115, 122, 40}, },
            {{48, 109, -44}, {110, 110, 85}, {111, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 90, -21}, {97, 111, 40}, {112, 112, 86}, {113, 122, 40}, },
            {{48, 90, -21}, {97, 115, 40}, {116, 116, 87}, {117, 122, 40}, },
            {{48, 90, -21}, {97, 102, 40}, {103, 103, 88}, {104, 122, 40}, },
            {{48, 90, -21}, {97, 117, 40}, {118, 118, 89}, {119, 122, 40}, },
            {{48, 109, -44}, {110, 110, 90}, {111, 122, 40}, },
            {{48, 90, -21}, {97, 118, 40}, {119, 119, 91}, {120, 122, 40}, },
            {{48, 111, -55}, {112, 112, 92}, {113, 115, 40}, {116, 116, 93}, {117, 122, 40}, },
            {{48, 116, -47}, {117, 117, 94}, {118, 122, 40}, },
            {{48, 115, -56}, {116, 116, 95}, {117, 122, 40}, },
            {{48, 109, -44}, {110, 110, 96}, {111, 122, 40}, },
            {{48, 100, -24}, {101, 101, 97}, {102, 122, 40}, },
            {{48, 109, -44}, {110, 110, 98}, {111, 122, 40}, },
            {{48, 100, -24}, {101, 101, 99}, {102, 122, 40}, },
            {{48, 116, -47}, {117, 117, 100}, {118, 122, 40}, },
            {{48, 104, -49}, {105, 105, 101}, {106, 122, 40}, },
            {{32, 126, -38}, },
            {{32, 42, -38}, {43, 46, 68}, {47, 47, 102}, {48, 126, 68}, },
            {},
            {{10, 10, 103}, },
            {{10, 126, -39}, },
            {{48, 107, -25}, {108, 108, 104}, {109, 122, 40}, },
            {{48, 117, -58}, {118, 118, 105}, {119, 122, 40}, },
            {{48, 110, -22}, {111, 111, 106}, {112, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 104, -49}, {105, 105, 107}, {106, 122, 40}, },
            {{48, 90, -21}, {97, 114, 40}, {115, 115, 108}, {116, 122, 40}, },
            {{48, 90, -21}, {97, 97, 40}, {98, 98, 109}, {99, 122, 40}, },
            {{48, 118, -60}, {119, 119, 110}, {120, 122, 40}, },
            {{48, 101, -27}, {102, 102, 111}, {103, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 114, -80}, {115, 115, 112}, {116, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 90, -21}, {97, 98, 40}, {99, 99, 113}, {100, 122, 40}, },
            {{48, 110, -22}, {111, 111, 114}, {112, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 100, -24}, {101, 101, 115}, {102, 122, 40}, },
            {{48, 98, -87}, {99, 99, 116}, {100, 122, 40}, },
            {{48, 100, -24}, {101, 101, 117}, {102, 122, 40}, },
            {{48, 107, -25}, {108, 108, 118}, {109, 122, 40}, },
            {{48, 116, -47}, {117, 117, 119}, {118, 122, 40}, },
            {{48, 109, -44}, {110, 110, 120}, {111, 122, 40}, },
            {{48, 57, 39}, {65, 66, 40}, {67, 67, 121}, {68, 86, 40}, {87, 87, 122}, {88, 90, 40}, {97, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 115, -56}, {116, 116, 123}, {117, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 109, -44}, {110, 110, 124}, {111, 122, 40}, },
            {{48, 100, -24}, {101, 101, 125}, {102, 122, 40}, },
            {{48, 107, -25}, {108, 108, 126}, {109, 122, 40}, },
            {{10, 10, 127}, {13, 13, 128}, {32, 126, -38}, },
            {},
            {{48, 100, -24}, {101, 101, 129}, {102, 122, 40}, },
            {{48, 90, -21}, {97, 97, 130}, {98, 122, 40}, },
            {{48, 113, -52}, {114, 114, 131}, {115, 122, 40}, },
            {{48, 109, -44}, {110, 110, 132}, {111, 122, 40}, },
            {{48, 104, -49}, {105, 105, 133}, {106, 122, 40}, },
            {{48, 107, -25}, {108, 108, 134}, {109, 122, 40}, },
            {{48, 57, 39}, {65, 83, 40}, {84, 84, 135}, {85, 90, 40}, {97, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 100, -24}, {101, 101, 136}, {102, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 113, -52}, {114, 114, 137}, {115, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 104, -49}, {105, 105, 138}, {106, 122, 40}, },
            {{48, 113, -52}, {114, 114, 139}, {115, 122, 40}, },
            {{48, 90, -21}, {97, 97, 140}, {98, 122, 40}, },
            {{48, 113, -52}, {114, 114, 141}, {115, 122, 40}, },
            {{48, 99, -50}, {100, 100, 142}, {101, 122, 40}, },
            {{48, 110, -22}, {111, 111, 143}, {112, 122, 40}, },
            {{48, 104, -49}, {105, 105, 144}, {106, 122, 40}, },
            {{48, 98, -87}, {99, 99, 145}, {100, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 100, -24}, {101, 101, 146}, {102, 122, 40}, },
            {},
            {{10, 10, 147}, },
            {{48, 90, -21}, {97, 97, 148}, {98, 122, 40}, },
            {{48, 114, -80}, {115, 115, 149}, {116, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 100, -24}, {101, 101, 150}, {102, 122, 40}, },
            {{48, 109, -44}, {110, 110, 151}, {111, 122, 40}, },
            {{48, 100, -24}, {101, 101, 152}, {102, 122, 40}, },
            {{48, 110, -22}, {111, 111, 153}, {112, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 115, -56}, {116, 116, 154}, {117, 122, 40}, },
            {{48, 107, -25}, {108, 108, 155}, {109, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 98, -87}, {99, 99, 156}, {100, 122, 40}, },
            {{48, 109, -44}, {110, 110, 157}, {111, 122, 40}, },
            {{48, 57, 39}, {65, 69, 40}, {70, 70, 158}, {71, 71, 40}, {72, 72, 159}, {73, 83, 40}, {84, 84, 160}, {85, 122, -112}, },
            {{48, 107, -25}, {108, 108, 161}, {109, 122, 40}, },
            {{48, 99, -50}, {100, 100, 162}, {101, 122, 40}, },
            {{48, 103, -34}, {104, 104, 163}, {105, 122, 40}, },
            {{48, 122, -21}, },
            {},
            {{48, 109, -44}, {110, 110, 164}, {111, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 90, -21}, {97, 97, 165}, {98, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 100, -24}, {101, 101, 166}, {102, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 104, -49}, {105, 105, 167}, {106, 122, 40}, },
            {{48, 116, -47}, {117, 117, 168}, {118, 122, 40}, },
            {{48, 100, -24}, {101, 101, 169}, {102, 122, 40}, },
            {{48, 110, -22}, {111, 111, 170}, {112, 122, 40}, },
            {{48, 115, -56}, {116, 116, 171}, {117, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 113, -52}, {114, 114, 172}, {115, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 117, -58}, {118, 118, 173}, {119, 122, 40}, },
            {{48, 109, -44}, {110, 110, 174}, {111, 122, 40}, },
            {{48, 109, -44}, {110, 110, 175}, {111, 122, 40}, },
            {{48, 113, -52}, {114, 114, 176}, {115, 122, 40}, },
            {{48, 103, -34}, {104, 104, 177}, {105, 122, 40}, },
            {{48, 115, -56}, {116, 116, 178}, {117, 122, 40}, },
            {{48, 100, -24}, {101, 101, 179}, {102, 122, 40}, },
            {{48, 99, -50}, {100, 100, 180}, {101, 122, 40}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 113, -52}, {114, 114, 181}, {115, 122, 40}, },
            {{48, 100, -24}, {101, 101, 182}, {102, 122, 40}, },
            {{48, 99, -50}, {100, 100, 183}, {101, 122, 40}, },
            {{48, 122, -21}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 51, 51, 51, 51, 12, 3, 7, 8, 5, 10, 4, 11, 1, 55, 9, 14, 0, 15, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 2, 6, 51, -1, -1, 13, 54, 54, 54, 54, 54, 54, 16, 54, 54, 54, 54, 54, 54, 23, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, -1, -1, 52, 52, -1, 54, 54, 54, 48, 54, 54, 54, 54, 54, 17, 54, 18, 54, 54, 34, 50, 54, 54, 54, 54, 54, 54, 54, 47, 54, 49, 54, 54, 54, -1, 52, 54, 54, 54, 54, 54, 54, 39, 22, 54, 33, 54, 38, 54, 54, 54, 54, 54, 54, 54, 54, 24, 21, 54, 53, 53, 54, 54, 28, 54, 54, 54, 54, 20, 54, 54, 43, 54, 54, 54, 54, 54, 54, 19, 53, 54, 26, 29, 54, 35, 40, 30, 27, 54, 25, 54, 54, 54, 54, 54, 32, 36, 54, 37, 54, 54, 54, 54, 54, 54, 54, 54, 45, 41, 42, 31, 44, 54, 54, 54, 46, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
