/* This file was generated by SableCC (http://www.sablecc.org/). */

package dessinart.syntax.lexer;

import java.io.*;
import dessinart.syntax.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssign(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDivide(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBr(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBr(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStar(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSc(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNot(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEq(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLt(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGt(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDo(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnd(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFor(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalse(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTrue(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElif(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThen(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReturn(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCanvas(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPencil(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColor(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDefine(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TImport(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDessinart(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSketch(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFunc(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInt(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDouble(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolean(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReplace(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMove(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDraw(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDrawTo(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetColor(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetWidth(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPower(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRoundfive(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRoundten(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRoundhund(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSin(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCos(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTan(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLog(line, pos); }
    Token new52(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new53(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }
    Token new54(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCommentMulti(text, line, pos); }
    Token new55(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdent(text, line, pos); }
    Token new56(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {37, 37, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 57, 15}, {59, 59, 16}, {60, 60, 17}, {61, 61, 18}, {62, 62, 19}, {65, 90, 20}, {97, 97, 20}, {98, 98, 21}, {99, 99, 22}, {100, 100, 23}, {101, 101, 24}, {102, 102, 25}, {103, 104, 20}, {105, 105, 26}, {106, 107, 20}, {108, 108, 27}, {109, 109, 28}, {110, 111, 20}, {112, 112, 29}, {113, 113, 20}, {114, 114, 30}, {115, 115, 31}, {116, 116, 32}, {117, 118, 20}, {119, 119, 33}, {120, 122, 20}, {123, 123, 34}, {125, 125, 35}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 36}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{42, 42, 37}, {47, 47, 38}, },
            {{48, 57, 15}, },
            {},
            {},
            {{61, 61, 39}, },
            {},
            {{48, 57, 40}, {65, 90, 41}, {97, 122, 41}, },
            {{48, 90, -22}, {97, 110, 41}, {111, 111, 42}, {112, 122, 41}, },
            {{48, 90, -22}, {97, 97, 43}, {98, 110, 41}, {111, 111, 44}, {112, 122, 41}, },
            {{48, 90, -22}, {97, 100, 41}, {101, 101, 45}, {102, 110, 41}, {111, 111, 46}, {112, 113, 41}, {114, 114, 47}, {115, 122, 41}, },
            {{48, 90, -22}, {97, 107, 41}, {108, 108, 48}, {109, 109, 41}, {110, 110, 49}, {111, 122, 41}, },
            {{48, 90, -22}, {97, 97, 50}, {98, 110, 41}, {111, 111, 51}, {112, 116, 41}, {117, 117, 52}, {118, 122, 41}, },
            {{48, 90, -22}, {97, 101, 41}, {102, 102, 53}, {103, 108, 41}, {109, 109, 54}, {110, 110, 55}, {111, 122, 41}, },
            {{48, 110, -23}, {111, 111, 56}, {112, 122, 41}, },
            {{48, 110, -23}, {111, 111, 57}, {112, 122, 41}, },
            {{48, 100, -25}, {101, 101, 58}, {102, 110, 41}, {111, 111, 59}, {112, 122, 41}, },
            {{48, 100, -25}, {101, 101, 60}, {102, 110, 41}, {111, 111, 61}, {112, 122, 41}, },
            {{48, 100, -25}, {101, 101, 62}, {102, 104, 41}, {105, 105, 63}, {106, 106, 41}, {107, 107, 64}, {108, 122, 41}, },
            {{48, 90, -22}, {97, 97, 65}, {98, 103, 41}, {104, 104, 66}, {105, 113, 41}, {114, 114, 67}, {115, 122, 41}, },
            {{48, 90, -22}, {97, 103, 41}, {104, 104, 68}, {105, 122, 41}, },
            {},
            {},
            {{9, 32, -2}, },
            {{32, 41, 69}, {42, 42, 70}, {43, 126, 69}, },
            {{10, 10, 71}, {13, 13, 72}, {32, 126, 73}, },
            {},
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 110, -23}, {111, 111, 74}, {112, 122, 41}, },
            {{48, 90, -22}, {97, 109, 41}, {110, 110, 75}, {111, 122, 41}, },
            {{48, 107, -26}, {108, 108, 76}, {109, 114, 41}, {115, 115, 77}, {116, 122, 41}, },
            {{48, 101, -28}, {102, 102, 78}, {103, 114, 41}, {115, 115, 79}, {116, 122, 41}, },
            {{48, 90, -22}, {97, 116, 41}, {117, 117, 80}, {118, 122, 41}, },
            {{48, 90, -22}, {97, 97, 81}, {98, 122, 41}, },
            {{48, 90, -22}, {97, 104, 41}, {105, 105, 82}, {106, 122, 41}, },
            {{48, 90, -22}, {97, 99, 41}, {100, 100, 83}, {101, 122, 41}, },
            {{48, 107, -26}, {108, 108, 84}, {109, 122, 41}, },
            {{48, 90, -22}, {97, 113, 41}, {114, 114, 85}, {115, 122, 41}, },
            {{48, 109, -45}, {110, 110, 86}, {111, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 90, -22}, {97, 111, 41}, {112, 112, 87}, {113, 122, 41}, },
            {{48, 90, -22}, {97, 115, 41}, {116, 116, 88}, {117, 122, 41}, },
            {{48, 90, -22}, {97, 102, 41}, {103, 103, 89}, {104, 122, 41}, },
            {{48, 90, -22}, {97, 117, 41}, {118, 118, 90}, {119, 122, 41}, },
            {{48, 109, -45}, {110, 110, 91}, {111, 122, 41}, },
            {{48, 90, -22}, {97, 118, 41}, {119, 119, 92}, {120, 122, 41}, },
            {{48, 111, -56}, {112, 112, 93}, {113, 115, 41}, {116, 116, 94}, {117, 122, 41}, },
            {{48, 116, -48}, {117, 117, 95}, {118, 122, 41}, },
            {{48, 115, -57}, {116, 116, 96}, {117, 122, 41}, },
            {{48, 109, -45}, {110, 110, 97}, {111, 122, 41}, },
            {{48, 100, -25}, {101, 101, 98}, {102, 122, 41}, },
            {{48, 109, -45}, {110, 110, 99}, {111, 122, 41}, },
            {{48, 100, -25}, {101, 101, 100}, {102, 122, 41}, },
            {{48, 116, -48}, {117, 117, 101}, {118, 122, 41}, },
            {{48, 104, -50}, {105, 105, 102}, {106, 122, 41}, },
            {{32, 126, -39}, },
            {{32, 42, -39}, {43, 46, 69}, {47, 47, 103}, {48, 126, 69}, },
            {},
            {{10, 10, 104}, },
            {{10, 126, -40}, },
            {{48, 107, -26}, {108, 108, 105}, {109, 122, 41}, },
            {{48, 117, -59}, {118, 118, 106}, {119, 122, 41}, },
            {{48, 110, -23}, {111, 111, 107}, {112, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 104, -50}, {105, 105, 108}, {106, 122, 41}, },
            {{48, 90, -22}, {97, 114, 41}, {115, 115, 109}, {116, 122, 41}, },
            {{48, 90, -22}, {97, 97, 41}, {98, 98, 110}, {99, 122, 41}, },
            {{48, 118, -61}, {119, 119, 111}, {120, 122, 41}, },
            {{48, 101, -28}, {102, 102, 112}, {103, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 114, -81}, {115, 115, 113}, {116, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 90, -22}, {97, 98, 41}, {99, 99, 114}, {100, 122, 41}, },
            {{48, 110, -23}, {111, 111, 115}, {112, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 100, -25}, {101, 101, 116}, {102, 122, 41}, },
            {{48, 98, -88}, {99, 99, 117}, {100, 122, 41}, },
            {{48, 100, -25}, {101, 101, 118}, {102, 122, 41}, },
            {{48, 107, -26}, {108, 108, 119}, {109, 122, 41}, },
            {{48, 116, -48}, {117, 117, 120}, {118, 122, 41}, },
            {{48, 109, -45}, {110, 110, 121}, {111, 122, 41}, },
            {{48, 57, 40}, {65, 66, 41}, {67, 67, 122}, {68, 86, 41}, {87, 87, 123}, {88, 90, 41}, {97, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 115, -57}, {116, 116, 124}, {117, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 109, -45}, {110, 110, 125}, {111, 122, 41}, },
            {{48, 100, -25}, {101, 101, 126}, {102, 122, 41}, },
            {{48, 107, -26}, {108, 108, 127}, {109, 122, 41}, },
            {{10, 10, 128}, {13, 13, 129}, {32, 126, -39}, },
            {},
            {{48, 100, -25}, {101, 101, 130}, {102, 122, 41}, },
            {{48, 90, -22}, {97, 97, 131}, {98, 122, 41}, },
            {{48, 113, -53}, {114, 114, 132}, {115, 122, 41}, },
            {{48, 109, -45}, {110, 110, 133}, {111, 122, 41}, },
            {{48, 104, -50}, {105, 105, 134}, {106, 122, 41}, },
            {{48, 107, -26}, {108, 108, 135}, {109, 122, 41}, },
            {{48, 57, 40}, {65, 83, 41}, {84, 84, 136}, {85, 90, 41}, {97, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 100, -25}, {101, 101, 137}, {102, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 113, -53}, {114, 114, 138}, {115, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 104, -50}, {105, 105, 139}, {106, 122, 41}, },
            {{48, 113, -53}, {114, 114, 140}, {115, 122, 41}, },
            {{48, 90, -22}, {97, 97, 141}, {98, 122, 41}, },
            {{48, 113, -53}, {114, 114, 142}, {115, 122, 41}, },
            {{48, 99, -51}, {100, 100, 143}, {101, 122, 41}, },
            {{48, 110, -23}, {111, 111, 144}, {112, 122, 41}, },
            {{48, 104, -50}, {105, 105, 145}, {106, 122, 41}, },
            {{48, 98, -88}, {99, 99, 146}, {100, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 100, -25}, {101, 101, 147}, {102, 122, 41}, },
            {},
            {{10, 10, 148}, },
            {{48, 90, -22}, {97, 97, 149}, {98, 122, 41}, },
            {{48, 114, -81}, {115, 115, 150}, {116, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 100, -25}, {101, 101, 151}, {102, 122, 41}, },
            {{48, 109, -45}, {110, 110, 152}, {111, 122, 41}, },
            {{48, 100, -25}, {101, 101, 153}, {102, 122, 41}, },
            {{48, 110, -23}, {111, 111, 154}, {112, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 115, -57}, {116, 116, 155}, {117, 122, 41}, },
            {{48, 107, -26}, {108, 108, 156}, {109, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 98, -88}, {99, 99, 157}, {100, 122, 41}, },
            {{48, 109, -45}, {110, 110, 158}, {111, 122, 41}, },
            {{48, 57, 40}, {65, 69, 41}, {70, 70, 159}, {71, 71, 41}, {72, 72, 160}, {73, 83, 41}, {84, 84, 161}, {85, 122, -113}, },
            {{48, 107, -26}, {108, 108, 162}, {109, 122, 41}, },
            {{48, 99, -51}, {100, 100, 163}, {101, 122, 41}, },
            {{48, 103, -35}, {104, 104, 164}, {105, 122, 41}, },
            {{48, 122, -22}, },
            {},
            {{48, 109, -45}, {110, 110, 165}, {111, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 90, -22}, {97, 97, 166}, {98, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 100, -25}, {101, 101, 167}, {102, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 104, -50}, {105, 105, 168}, {106, 122, 41}, },
            {{48, 116, -48}, {117, 117, 169}, {118, 122, 41}, },
            {{48, 100, -25}, {101, 101, 170}, {102, 122, 41}, },
            {{48, 110, -23}, {111, 111, 171}, {112, 122, 41}, },
            {{48, 115, -57}, {116, 116, 172}, {117, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 113, -53}, {114, 114, 173}, {115, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 117, -59}, {118, 118, 174}, {119, 122, 41}, },
            {{48, 109, -45}, {110, 110, 175}, {111, 122, 41}, },
            {{48, 109, -45}, {110, 110, 176}, {111, 122, 41}, },
            {{48, 113, -53}, {114, 114, 177}, {115, 122, 41}, },
            {{48, 103, -35}, {104, 104, 178}, {105, 122, 41}, },
            {{48, 115, -57}, {116, 116, 179}, {117, 122, 41}, },
            {{48, 100, -25}, {101, 101, 180}, {102, 122, 41}, },
            {{48, 99, -51}, {100, 100, 181}, {101, 122, 41}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 113, -53}, {114, 114, 182}, {115, 122, 41}, },
            {{48, 100, -25}, {101, 101, 183}, {102, 122, 41}, },
            {{48, 99, -51}, {100, 100, 184}, {101, 122, 41}, },
            {{48, 122, -22}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 52, 52, 52, 52, 13, 4, 3, 8, 9, 6, 11, 5, 12, 1, 56, 10, 15, 0, 16, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 2, 7, 52, -1, -1, 14, 55, 55, 55, 55, 55, 55, 17, 55, 55, 55, 55, 55, 55, 24, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, -1, -1, 53, 53, -1, 55, 55, 55, 49, 55, 55, 55, 55, 55, 18, 55, 19, 55, 55, 35, 51, 55, 55, 55, 55, 55, 55, 55, 48, 55, 50, 55, 55, 55, -1, 53, 55, 55, 55, 55, 55, 55, 40, 23, 55, 34, 55, 39, 55, 55, 55, 55, 55, 55, 55, 55, 25, 22, 55, 54, 54, 55, 55, 29, 55, 55, 55, 55, 21, 55, 55, 44, 55, 55, 55, 55, 55, 55, 20, 54, 55, 27, 30, 55, 36, 41, 31, 28, 55, 26, 55, 55, 55, 55, 55, 33, 37, 55, 38, 55, 55, 55, 55, 55, 55, 55, 55, 46, 42, 43, 32, 45, 55, 55, 55, 47, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
